# yml 文件使用缩进表示层级关系， 缩进必须是用空格符，绝对不能使用制表符 tab \t
# 专业的yml编辑器，会自动的将tab 转成多个空格
# 相同的层级必须由相同的缩进空格
# :   冒号+空格，后面就是配置值

server:
   port: 80

spring:
   datasource:
      url: jdbc:mysql://188.131.166.87:3306/hilofruits?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      # 配置项之间可以有空行
      password: Sxq1&Liujun2
      # yml 支持驼峰命名 + -号分隔符
      driverClassName: com.mysql.jdbc.Driver
      #driver-class-name: com.mysql.jdbc.Driver
      
   # 相同的配置节点只能出现一次 
   # 邮件服务器配置（springboot 的配置项）
   mail:
      # 邮箱服务器地址
      host: smtp.qq.com
      # 用户名
      username: 1738636874@qq.com
      # 密码 
      password: cypilaojspkzfbhc
      default-encoding: UTF-8
      
# 以谁来发送邮件（自定义的配置信息）
mail:
   from:
      addr: 1738636874@qq.com


# springboot 日志输出配置
logging:
  level:
    # 下面是对指定的包下的日志输出进行设定
    # 日志级别： debug， info， warn， error
    com:
      yc:
        hilo:
          dao: debug
          web: warn
